const products = [
    {
        id: 1,
        userId: 'a',
        title: 'Samsung Galaxy s8 Phone',
        description: 'Immerse yourself in cutting-edge technology with the Samsung Galaxy s8 Phone. This sleek and powerful device redefines mobile communication, boasting a stunning display, advanced camera capabilities, and seamless performance. Elevate your smartphone experience with the Samsung Galaxy s8.',
        price: 99.99,
        category: 'Electronics',
        condition: 'used',
        img: 'https://media.wired.co.uk/photos/606da1d7d8817d4fe4c507ef/4:3/w_4032,h_3024,c_limit/img_0324-ad.jpg',
        location: 'Banff, Alberta, Canada',
        sold: false,
        createdAt: Date.now(),
    },
    {
        id: 2,
        userId: 'b',
        title: 'Garmin fenix 7X Pro Solar',
        description: ' Conquer your fitness goals with the Garmin fenix 7X Pro Solar. This premium sports watch is a beacon of innovation, featuring solar charging technology to keep you powered on your adventures. With advanced fitness tracking, GPS navigation, and a rugged design, the fenix 7X is your ultimate companion for the active lifestyle.',
        price: 899.99,
        category: 'Sports',
        condition: 'used',
        img: 'https://preview.redd.it/fenix-7x-pro-sapphire-solar-enjoying-the-uk-sunshine-v0-5xdw4kndpd5b1.jpg?width=640&crop=smart&auto=webp&s=83e33450e2d35280a42457c749342135b873d214',
        location: 'Manhattan, New York City, USA',
        sold: false,
        createdAt: Date.now(),
    },
    {
        id: 3,
        userId: 'c',
        title: 'Nike Sportswear',
        description: ' Embrace style and comfort with Nike Sportswear. This iconic t-shirt effortlessly blends fashion and functionality, making it a must-have in your wardrobe. Crafted from premium materials, it delivers a perfect fit while showcasing the renowned Nike logo. Elevate your streetwear game with the timeless appeal of Nike Sportswear.',
        price: 24.99,
        category: 'Fashion',
        condition: 'new',
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/eplrf7xfu6qpqstpcpvv/sportswear-t-shirt-FPcVXK.png',
        location: 'Malibu, California, USA',
        sold: false,
        createdAt: Date.now(),
    },
    {
        id: 4,
        userId: 'd',
        title: 'HOMCOM Dining Chairs Upholstered',
        description: 'Transform your dining space with the HOMCOM Dining Chairs Upholstered. These elegant chairs combine comfort and sophistication, featuring plush upholstery and a modern design. Whether hosting dinner parties or enjoying family meals, these chairs add a touch of luxury to your home.',
        price: 99.99,
        category: 'Home & Garden',
        condition: 'new',
        img: 'https://i.ebayimg.com/images/g/asoAAOSwUhdlS-Lk/s-l1600.jpg',
        location: 'Tokyo, Japan',
        sold: false,
        createdAt: Date.now(),
    },
    {
        id: 5,
        userId: 'f',
        title: 'Volkswagen Arteon',
        description: 'Experience driving excellence with the Volkswagen Arteon. This exceptional car seamlessly blends performance, style, and innovation. From its sleek exterior to its cutting-edge interior features, the Arteon is designed to provide a thrilling and comfortable driving experience. Make a statement on the road with the Volkswagen Arteon.',
        price: 20000,
        category: 'Cars & Motorbikes',
        condition: 'used',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/2018_Volkswagen_Arteon_2.0.jpg/280px-2018_Volkswagen_Arteon_2.0.jpg',
        location: 'Tuscany, Italy',
        sold: false,
        createdAt: Date.now(),
    },
]

const users = [
    {
        id: 'a',
        productsId: [1],
        favouriteProductsId: [2,3],
    },
    {
        id: 'b',
        productsId: [2],
        favouriteProductsId: [1,4],
    },
    {
        id: 'c',
        productsId: [3],
        favouriteProductsId: [5,1],
    },
    {
        id: 'd',
        productsId: [4],
        favouriteProductsId: [3,2],
    },
    {
        id: 'f',
        productsId: [5],
        favouriteProductsId: [4,3,2,1],
    },
]